### ISSUE TITLE
issues with inserting data

### ISSUE THREAD

**Issue by gutasaputra** [mjhea0/node-postgres-promises#14]
hi, i follow your tutorial 
http://mherman.org/blog/2016/03/13/designing-a-restful-api-with-node-and-postgres/#.WGvRmLZ95o5

i have some issue when inserting data, 

`function createPuppy(req, res, next) {
  req.body.age = parseInt(req.body.age);
  db.none('insert into pups(name, breed, age, sex)' +
      'values(${name}, ${breed}, ${age}, ${sex})',
    req.body)
    .then(function () {
      res.status(200)
        .json({
          status: 'success',
          message: 'Inserted one puppy'
        });
    })
    .catch(function (err) {
      return next(err);
    });
}`

if i use the same codes with yours, i will got the error. 
the message : TypeError: Cannot read property &#39;age&#39; of undefined

why this happen? i dont understand.

i try to change the codes.
i use body parser instead of following your tutorial.

> let age = req.body.age;

i will got the same error.

how to get the data?
it should be using body parser rite?
idk why i got the same eror.

Cannot read property &#39;name&#39; of undefined

please help me to fix this issue.
many thanks in advance.

**Comment by mjhea0** [comment]
How are you testing it out? Is any of the payload coming through? What happens when you log `req.body`?

```
console.log(req.body)
```

**Comment by gutasaputra** [comment]
hi, its already resolved. the problem is lies on the post man. 
i usually use post man as a tooles to help me to manipulate API data.

for other users that use postman, please make sure that you choose body-> x-www-form urlencoded.

make sure that you installed body parser.
catch the data using this synyax.
`req.body.field_name`

<img width="970" alt="screen shot 2017-01-04 at 9 09 53 am" src="https://cloud.githubusercontent.com/assets/1556126/21629746/99b2677a-d25d-11e6-8fde-029d0d461ca6.png">

thanks for your support.
