### ISSUE TITLE
404 status

### ISSUE THREAD

**Issue by mikeKane** [mjhea0/node-postgres-promises#17]
I have cloned the repo. Followed the directions. Went to localhost:3000 and received 

{"status":"error","message":{"status":404}}

What could I be doing wrong?

**Comment by mikeKane** [comment]
Terminal shows 

Mikes-MBP:node-postgres-promises-master _kane7161$ npm start

> node-postgres-promises@0.0.0 start /Users/_kane7161/Downloads/node-postgres-promises-master
> node ./bin/www

> GET /api/puppy 500 6.959 ms - 43
> GET /api/puppy 500 1.079 ms - 43


[puppy.txt](https://github.com/mjhea0/node-postgres-promises/files/1970790/puppy.txt)

**Comment by mjhea0** [comment]
I imagine it has something to do with the postgres database not being set up right or the connection string not being correct. Please review the comments from the [blog post](http://mherman.org/blog/2016/03/13/designing-a-restful-api-with-node-and-postgres) as this has been addressed. If you need further help add a new comment to the blog post.
