### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by vitaly-t** [mjhea0/node-postgres-promises#2]
``` js
function checkID(req, res, next) {
  var pupID = req.params.id;
  db.one('select id from pups where id = $1', pupID)
    .then(function(data) {
      return next();
    })
    .catch(function(err) {
      /* jshint ignore:start */
      res.status(400)
        .json({
          status: 'error',
          message: `ID '${pupID}' does not exist.`
        });
      /* jshint ignore:end */
    });
}
```

Code like this is not very accurate in a sense that you can get into the `.catch` section for multiple reasons, and only one reason really means that no record has been found:
- an issue with database connectivity
- more than 1 row was returned
- 0 rows returned

You are expecting the error to be the last one, but there 2 more as you see.

When an error relates to number of records returned, we can check it via:
`if(error instanceof pgp.QueryResultError)`

You wouldn't care about the connection problem in this context, but when locating a single record by id, method [oneOrNone](http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone) is more suitable, so you can check whether the resolved data is `null` or not, and then provide the response accordingly.

**Comment by mjhea0** [comment]
Good catch! So, that would work?

``` javascript
function checkID(req, res, next) {
  var pupID = req.params.id;
  db.any('select id from pups where id = $1', pupID)
    .then(function(data) {
      if(!data.length) {
        /* jshint ignore:start */
        res.status(400)
          .json({
            status: 'error',
            message: `ID '${pupID}' does not exist.`
          });
        /* jshint ignore:end */
      } else {
        return next();
      }
    })
    .catch(function(err) {
      return next(err);
    });
}
```

**Comment by vitaly-t** [comment]
Probably, depending on the type of `req.params.id`, but it doesn't make a very practical example.

The following one does it better:

``` js
function checkID(req, res, next) {
    var pupID = parseInt(req.params.id);
    db.oneOrNone('select id from pups where id = $1', pupID)
        .then(function(pup) {
            if(!pup) {
                /* jshint ignore:start */
                res.status(400)
                    .json({
                        status: 'error',
                        message: `ID '${pupID}' does not exist.`
                    });
                /* jshint ignore:end */
            } else {
                return next();
            }
        })
        .catch(function(err) {
            return next(err);
        });
}
```

**Comment by mjhea0** [comment]
Thanks!

**Comment by vitaly-t** [comment]
I think this method may need some change still...

``` js
function checkID(req, res, next) {
  var pupID = parseInt(req.params.id);
  db.oneOrNone('select id from pups where id = $1', pupID)
    .then(function(data) {
      if(!data) {
        /* jshint ignore:start */
        res.status(400)
          .json({
            status: 'error',
            message: `ID '${pupID}' does not exist.`
          });
        /* jshint ignore:end */
      } else {
        return next();
      }
    })
    .catch(function(err) {
      return next(err);
    });
}
```

this is a GET method to return some value. It reads data from the database and then returns nothing, just seems illogical. Or am I reading it wrong?

**Comment by mjhea0** [comment]
This is just a middleware function, so it just handles requests and responses, which means it doesn't need to explicitly return something. Feel free to suggest a different means of validating the ID.
