### ISSUE TITLE
missing variables

### ISSUE THREAD

**Issue by vitaly-t** [mjhea0/node-postgres-promises#3]
``` js
function validPayload(req, res, next) {
  var keys;
  if (req.method === 'POST') {
    keys = ['name', 'breed', 'age', 'sex'];
  } else if (req.method === 'PUT') {
    keys = ['column', 'value'];
  }
  keys.forEach(function(key){
    if(!(key in req.body)) {
      /* jshint ignore:start */
      return res.status(400)
        .json({
          status: 'error',
          message: `Invalid JSON. '${key}' does not exist.`
        });
      /* jshint ignore:end */
    }
  });
  return next();
}
```

With pg-promise, when you are using [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters), if you are referring to a parameter-property in query that's missing within the object, you will get the same type of error, `Property 'name' doesn't exist`.

This is just something to consider ;)

**Comment by mjhea0** [comment]
So, you don't think I'll need to check if the keys are there then?

**Comment by mjhea0** [comment]
``` sh
curl -X PUT --data "column=name" \
http://127.0.0.1:3000/api/puppies/1
```

That will update the name to `null`.

**Comment by vitaly-t** [comment]
Generally, an HTTP handler would check for all the keys it requires, and report an issue, before trying to access the database.

pg-promise allows you to use method [as.format](http://vitaly-t.github.io/pg-promise/formatting.html#.format) to format queries separate form executing them. But perhaps for an academic example this is too much.

**Comment by mjhea0** [comment]
@vitaly-t: Yes, that's probably a bit too much for this example. Thanks!

**Comment by mjhea0** [comment]
Also, I would probably use something like this anyway -> https://www.npmjs.com/package/isvalid
