### ISSUE TITLE
article notes

### ISSUE THREAD

**Issue by vitaly-t** [mjhea0/node-postgres-promises#4]
After my initial read of the article: http://mherman.org/blog/2016/03/13/designing-a-restful-api-with-node-and-postgres/

I made a list of notes/suggestions.
- In your installation instructions you are using specific library versions, which compels people to just copy'n paste it and use those versions instead of the latest ones. May I advise not to include specific library versions during the installation steps?

> Put simply, pg-promise abstracts away much of the difficult, low-level connection management, allowing you to focus on the business logic.

Connection management is just one aspect of simplification provided by the library. The other main two include automated transactions and a powerful query formatting engine (unlike the very basic one that’s in node-postgres).
- In your demo you show the use of Bluebird, but never mention why. It would worth pointing that it is recommended as the best promise library today.

> Besides, any, you can use the following Query Result Masks:

There you list only some methods, which makes one think that this is it. But there are very important methods, such as [oneOrNone](http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone) and [manyOrNone](http://vitaly-t.github.io/pg-promise/Database.html#.manyOrNone) = [any](http://vitaly-t.github.io/pg-promise/Database.html#.any) that are needed frequently, not to mention super-important methods [task](http://vitaly-t.github.io/pg-promise/Database.html#.task) and [tx](http://vitaly-t.github.io/pg-promise/Database.html#.tx) that are unfortunately not covered by the article in any way.

> Did you notice the ~ in the SQL query? This is used to prevent SQL injection by properly escaping the variable.

It would be more accurate to say that `~` or `:name` (since version 3.2.1) is to correctly escape SQL names and identifiers, which in addition isolates possible SQL hijacking via SQL names (as another effect).

> So, we used the result Query Result Mask, in order to output the number of rows removed from the database.

It would probably help more to generalize like this: `in order to get the number of records affected by the query.`, because this is a valid approach for such operations as `INSERT`, `UPDATE` and `DELETE`.

In conslusion, I'd want to say thank you for your efforts with the article, it is very good! My only regret - it doesn't cover such important aspects of the library as the use of [tasks](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks) and [transactions](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#transactions).

**Comment by vitaly-t** [comment]
@mjhea0 Do you need help with this? Please let me know.

**Comment by mjhea0** [comment]
@vitaly-t Yes I am slammed right now and won't have time to update until next week. If you can help by issuing PRs then I'll update the blog post. Sound good? Thanks so much!

**Comment by mjhea0** [comment]
updated
