### ISSUE TITLE
Uses two identical queries

### ISSUE THREAD

**Issue by JensGutermuth** [mjhea0/node-postgres-promises#5]
These two queries are exactly the same and both get executed for a single request:
- [`get SINGLE puppy`](https://github.com/mjhea0/node-postgres-promises/blob/master/routes/index.js#L36-L37)
- [`checkID`](https://github.com/mjhea0/node-postgres-promises/blob/master/routes/index.js#L109-L110)

I know it makes the code a bit shorter and arguably nicer, but this seems pretty wasteful and bad practice in any real-world-code.

It also introduces a race condition, because those two queries are not using a transaction: Take to requests `DELETE /api/puppies/1` (referred to as `DEL`) and `GET /api/puppies/1` (referred to as `GET` and assume the following chain of events:
- `DEL` executes `checkID`, finds puppy `1`
- `GET` executes `checkID`, finds puppy `1`
- `DEL` deletes puppy `1`
- `GET` will not find puppy `1` and return 500

That's not terrible ("just" a wrong error code), but also far from great. The `GET` request above can also be exchanged with an `PUT` request.

**Comment by vitaly-t** [comment]
You are looking at it from a higher business logic, which indeed requires consideration for the sequence of commands that would be issued, and possible use of transactions.

The article is a bit simpler than that, it just shows how to execute basic queries.

**Comment by JensGutermuth** [comment]
I think demos using patterns (like the check-and-then-select-again thing here), that just cannot be used in any real code, are misleading and don't help anyone. An unexperienced developer might copy&paste the code and will later tear her / his hair out trying to debug an issue that only rarely and seemingly randomly pops up. I've had this class of problem in production code before and it was a lot more painful to deal with it as an afterthought.

**Comment by vitaly-t** [comment]
> An inexperienced developer might copy&paste the code and will later tear her / his hair out.

I agree, they do copy'n paste all the time. I work with developers who have poor understanding of Promises and databases, and they always end up with a mess, no matter how good was the demo they copied :)

Let's hope Michael makes time for the corrections you suggested ;)

**Comment by mjhea0** [comment]
@Delphinator and @vitaly-t - I agree with both of you. In fact, it is a big concern for me as well, as I have found out that many professional developers are simply copying and pasting much of my code, which eventually ends up in production. This is by far from production code. In fact, it's simply a basic example to get started.

That said, I think the code should be updated. But I'd rather not add transactions into this beginner post. Want to issue a PR with updates?

**Comment by vitaly-t** [comment]
Speaking of practical examples, I always keep working on that on my end, and I just added a new example: [select->insert](https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md).

Maybe it will give you an idea of how to improve your demo. You can seer there that transactions aren't that scary really, and they are needed way too often.

**Comment by mjhea0** [comment]
updated to pass all errors to the express error handler
