### ISSUE TITLE
Can change id field

### ISSUE THREAD

**Issue by JensGutermuth** [mjhea0/node-postgres-promises#6]
Changing a primary key (especially one that's automatically generated and has no meaning outside of the system) is bad practice. Things that could happen:
- An outside system now has broken references, because it wasn't notified about the changed primary key
- If you set the id to some value greater than the highest currenty-existing one, one future `POST` request will fail with a constraint validation.

You could probably just check `req.body.column` to be not-equal to `'id'` somewhere before https://github.com/mjhea0/node-postgres-promises/blob/master/routes/index.js#L72

**Comment by mjhea0** [comment]
Agreed. @Delphinator would you be able to submit a PR? Then I'll update the blog post.

**Comment by mjhea0** [comment]
updated
