### ISSUE TITLE
more issues

### ISSUE THREAD

**Issue by JensGutermuth** [mjhea0/node-postgres-promises#7]
I'm honestly to lazy to put all of these into seperate issues, so here you go:
- user can only change one field per request
- `DELETE` will return `success` even though no record was deleted (_could_ be valid behaviour. Idempotence and all...)
- returns 400 for a missing entity (404 Not Found would be appropiate)

Additional topics to make the tutorial more than very-basics level:
- pagination
- filtering
- relations

**Comment by vitaly-t** [comment]
> Additional topics to make the tutorial more than very-basics level

I agree about the relations, but filtering and pagination is way outside of an entry article such as this one.

It is supposed to be an ABC for pulling and returning data from a REST service ;)

**Comment by mjhea0** [comment]
@Delphinator - again, I'd love a PR. I'm extremely busy at the moment and taking an actual vacation over the weekend. I also agree that adding basic relations would be nice. I'll look into it. Thanks again!

**Comment by mjhea0** [comment]
updated (minus relations)
